# Generated by Django 4.0.2 on 2022-02-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_products_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='prod_id',
        ),
        migrations.AddField(
            model_name='orders',
            name='prod_id',
            field=models.ManyToManyField(to='main_app.Products'),
        ),
    ]
